# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

notarize:
  macos:
    - enabled: '{{ isEnvSet "MACOS_SIGN_P12" }}'
      ids:
        - onekeymap-cli
      sign:
        certificate: "{{.Env.MACOS_SIGN_P12}}"
        password: "{{.Env.MACOS_SIGN_PASSWORD}}"

      notarize:
        issuer_id: "{{.Env.MACOS_NOTARY_ISSUER_ID}}"
        key_id: "{{.Env.MACOS_NOTARY_KEY_ID}}"
        key: "{{.Env.MACOS_NOTARY_KEY}}"
        wait: true
        timeout: 10m

builds:
  - id: onekeymap-cli
    main: ./cmd/onekeymap-cli
    binary: onekeymap-cli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/xinnjie/onekeymap-cli/internal/cmd.version={{.Version}}

archives:
  - id: onekeymap-cli
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: ['zip']
    files:
      - README.md
      - LICENSE.md
      - completions/*

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ .Tag }}-devel"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^refactor:"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: xinnjie
    name: onekeymap-cli
  draft: false
  prerelease: auto
  name_template: "onekeymap-cli {{.Version}}"
  footer: |
    ## Installation

    ### macOS
    ```bash
    brew tap xinnjie/onekeymap
    brew install onekeymap-cli
    ```

    ### Linux

    #### Debian/Ubuntu (deb)
    ```bash
    wget https://github.com/xinnjie/onekeymap-cli/releases/download/{{.Tag}}/onekeymap-cli_{{.Version}}_x86_64.deb
    sudo dpkg -i onekeymap-cli_{{.Version}}_x86_64.deb
    ```

    #### Fedora/RHEL/CentOS (rpm)
    ```bash
    wget https://github.com/xinnjie/onekeymap-cli/releases/download/{{.Tag}}/onekeymap-cli_{{.Version}}_x86_64.rpm
    sudo rpm -i onekeymap-cli_{{.Version}}_x86_64.rpm
    ```

    #### Alpine (apk)
    ```bash
    wget https://github.com/xinnjie/onekeymap-cli/releases/download/{{.Tag}}/onekeymap-cli_{{.Version}}_x86_64.apk
    sudo apk add --allow-untrusted onekeymap-cli_{{.Version}}_x86_64.apk
    ```

    #### Manual installation (Linux/macOS)
    ```bash
    tar -xzf onekeymap-cli_*.tar.gz
    sudo mv onekeymap-cli /usr/local/bin/
    ```

    ### Windows
    Extract the zip file and add the directory to your PATH.

winget:
  - name: onekeymap-cli
    publisher: xinnjie
    license: MIT
    license_url: "https://github.com/xinnjie/onekeymap-cli/blob/main/LICENSE.md"
    homepage: https://github.com/xinnjie/onekeymap-cli
    short_description: "Universal keymap configuration tool for VSCode, Zed, IntelliJ and more"
    description: |
      OneKeymap CLI is a powerful command-line tool that lets you import, export, and synchronize keyboard shortcuts between VSCode, IntelliJ IDEA, Zed, Helix, and more.
      Stop reconfiguring keybindings every time you switch editors—maintain one universal keymap and deploy it everywhere.
    repository:
      owner: xinnjie
      name: winget-pkgs
      branch: "onekeymap-cli-{{.Version}}"
      token: "{{ .Env.WINGET_GITHUB_TOKEN }}"
      pull_request:
        enabled: true
        draft: true
        base:
          owner: microsoft
          name: winget-pkgs
          branch: master

homebrew_casks:
  - name: onekeymap-cli
    repository:
      owner: xinnjie
      name: homebrew-onekeymap
      token: "{{ .Env.HOMEBREW_GITHUB_TOKEN }}"
    homepage: https://github.com/xinnjie/homebrew-onekeymap
    description: "Universal keymap configuration tool for VSCode, Zed, IntelliJ and more"
    binary: onekeymap-cli
    completions:
      bash: completions/onekeymap-cli.bash
      zsh: completions/_onekeymap-cli
      fish: completions/onekeymap-cli.fish

# generate universal binaries for osx, see https://goreleaser.com/customization/universalbinaries/
universal_binaries:
- replace: true
  name_template: 'onekeymap-cli'

nfpms:
  - id: onekeymap-cli
    package_name: onekeymap-cli
    file_name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    vendor: xinnjie
    homepage: https://github.com/xinnjie/onekeymap-cli
    maintainer: xinnjie
    description: Universal keymap configuration tool for VSCode, Zed, IntelliJ and more
    license: MIT
    formats:
      - deb
      - rpm
      - apk
    bindir: /usr/bin
    contents:
      - src: ./completions/onekeymap-cli.bash
        dst: /usr/share/bash-completion/completions/onekeymap-cli
        file_info:
          mode: 0644
      - src: ./completions/_onekeymap-cli
        dst: /usr/share/zsh/site-functions/_onekeymap-cli
        file_info:
          mode: 0644
      - src: ./completions/onekeymap-cli.fish
        dst: /usr/share/fish/vendor_completions.d/onekeymap-cli.fish
        file_info:
          mode: 0644
      - src: ./LICENSE.md
        dst: /usr/share/doc/onekeymap-cli/LICENSE.md
        file_info:
          mode: 0644
      - src: ./README.md
        dst: /usr/share/doc/onekeymap-cli/README.md
        file_info:
          mode: 0644
