mappings:
  - id: "actions.clipboard.cut"
    name: "Cut text"
    description: "Cut selected text/file"
    category: "Editor.Clipboard"
    vscode:
      - command: "editor.action.clipboardCutAction"
        when: "editorTextFocus"
      # cut in file explorer
      - command: "filesExplorer.cut"
        when: "filesExplorerFocus && foldersViewVisible && !explorerResourceIsRoot && !explorerResourceReadonly && !inputFocus"
        disableImport: true
      # underlying cut
      - command: "execCut"
        disableImport: true
    zed:
      - action: "editor::Cut"
        context: "Editor"
      - action: "project_panel::Cut"
        context: "ProjectPanel"
    intellij:
      action: "$Cut"
    helix:
      command: "delete_selection"
      mode: "insert"
  - id: "actions.clipboard.copy"
    name: "Copy text"
    description: "Copy selected text/file"
    category: "Editor.Clipboard"
    vscode:
      - command: "editor.action.clipboardCopyAction"
        when: "editorTextFocus"
      # copy in file explorer
      - command: "filesExplorer.copy"
        disableImport: true
        when: "filesExplorerFocus && foldersViewVisible && !explorerResourceIsRoot && !inputFocus"
      # copy in problem view
      - command: "problems.action.copy"
        when: "problemsVisibility && !relatedInformationFocus && focusedView == 'workbench.panel.markers.view'"
        disableImport: true
      # underlying copy
      - command: "execCopy"
        disableImport: true
    zed:
      - action: "editor::Copy"
        context: "Editor"
      # copy in terminal
      - action: "terminal::Copy"
        context: "Terminal"
      # copy in markdown
      - action: "markdown::Copy"
        context: "Markdown"
      - action: "project_panel::Copy"
        context: "ProjectPanel"
    intellij:
      action: "$Copy"
    helix:
      command: "yank_to_clipboard"
      mode: "insert"
  - id: "actions.clipboard.paste"
    name: "Paste text"
    description: "Paste text/file"
    category: "Editor.Clipboard"
    vscode:
      - command: "editor.action.clipboardPasteAction"
        when: "editorTextFocus && !editorReadonly"
      # paste in file explorer
      - command: "filesExplorer.paste"
        when: "filesExplorerFocus && foldersViewVisible && !explorerResourceReadonly && !inputFocus"
        disableImport: true
      # underlying paste
      - command: "execPaste"
        disableImport: true
    zed:
      - action: "editor::Paste"
        context: "Editor"
      # paste in terminal
      - action: "terminal::Paste"
        context: "Terminal"
      - action: "project_panel::Paste"
        context: "ProjectPanel"
    intellij:
      action: "$Paste"
    helix:
      command: "paste_clipboard_after"
      mode: "insert"
  - id: "actions.clipboard.copyFilePath"
    name: "Copy file path"
    description: "Copy file path"
    category: "Editor.Clipboard"
    vscode:
      command: "copyFilePath"
      when: "filesExplorerFocus"
    zed:
      action: "workspace::CopyPath"
      context: ""
    intellij:
      action: "CopyPaths"
    helix:
      notSupported: true
