mappings:
  - id: "actions.go.nextChange"
    name: "Next change"
    description: "Go to next change"
    category: "Navigation.DirtyDiff"
    vscode:
      command: "editor.action.dirtydiff.next"
      when: "editorTextFocus"
    zed:
      action: "editor::GoToNextChange"
      context: "Editor"
    intellij:
      action: "VcsShowNextChangeMarker"
  - id: "actions.go.previousChange"
    name: "Previous change"
    description: "Go to previous change"
    category: "Navigation.DirtyDiff"
    vscode:
      command: "editor.action.dirtydiff.previous"
      when: "editorTextFocus"
    zed:
      action: "editor::GoToPreviousChange"
      context: "Editor"
    intellij:
      action: "VcsShowPrevChangeMarker"
