# Additional mappings for DisableImport importer tests
mappings:
  # DisableImport preference among command+args ignoring when
  - id: "actions.test.forimport.withArgs.A"
    description: "DisableImport args candidate A (disabled)"
    category: "Testing"
    vscode:
      - command: "cmd.forimp.args"
        when: "W_A"
        args:
          x: 1
        disableImport: true
  - id: "actions.test.forimport.withArgs.B"
    description: "DisableImport args candidate B (enabled, preferred)"
    category: "Testing"
    vscode:
      - command: "cmd.forimp.args"
        when: "W_B"
        args:
          x: 1
  # DisableImport preference in command-only fallback (no args)
  - id: "actions.test.forimport.cmdOnly.A"
    description: "DisableImport cmd-only candidate A (disabled)"
    category: "Testing"
    vscode:
      - command: "cmd.forimp.noargs"
        when: "Y_A"
        disableImport: true
  - id: "actions.test.forimport.cmdOnly.B"
    description: "DisableImport cmd-only candidate B (enabled, preferred)"
    category: "Testing"
    vscode:
      - command: "cmd.forimp.noargs"
        when: "Y_B"
  # Single-entry implicit enabled vs multi-entry
  - id: "actions.test.forimport.singleImplicit"
    description: "Single-entry mapping implicitly enabled"
    category: "Testing"
    vscode:
      command: "cmd.forimp.single"
      when: "W_S"
  - id: "actions.test.forimport.multi"
    description: "Multi-entry mapping"
    category: "Testing"
    vscode:
      - command: "could.be.imported"
        when: "SomeCondition"
      - command: "should.not.import.command"
        when: "OtherCondition"
        disableImport: true
