mappings:
  - id: "actions.notebook.cell.edit"
    name: "Edit cell"
    description: "Edit Cell"
    category: "Tools.Jupyter Notebook"
    vscode:
      command: "notebook.cell.edit"
      when: "notebookCellListFocused && !editorHoverFocused && !inputFocus && !notebookOutputInputFocused"
    intellij:
      action: "NotebookEnterCell"
    zed:
      notSupported: true
      notSupportedReason: "Notebook not supported yet see [issue](https://github.com/zed-industries/zed/discussions/25936)"
  - id: "actions.notebook.cell.execute"
    name: "Execute cell"
    description: "Execute Cell"
    category: "Tools.Jupyter Notebook"
    vscode:
      command: "notebook.cell.execute"
      when: "notebookCellListFocused && notebookMissingKernelExtension && !notebookCellExecuting && notebookCellType == 'code' || notebookCellListFocused && !notebookCellExecuting && notebookCellType == 'code' && notebookKernelCount > 0 || notebookCellListFocused && !notebookCellExecuting && notebookCellType == 'code' && notebookKernelSourceCount > 0"
    intellij:
      action: "NotebookRunCell"
    zed:
      notSupported: true
      notSupportedReason: "Notebook not supported yet see [issue](https://github.com/zed-industries/zed/discussions/25936)"
  - id: "actions.notebook.cell.executeAndInsertBelow"
    name: "Execute and insert"
    description: "Execute Cell and Insert Below"
    category: "Tools.Jupyter Notebook"
    vscode:
      command: "notebook.cell.executeAndInsertBelow"
      when: "notebookCellListFocused && notebookCellType == 'markup' || notebookCellListFocused && notebookMissingKernelExtension && !notebookCellExecuting && notebookCellType == 'code' || notebookCellListFocused && !notebookCellExecuting && notebookCellType == 'code' && notebookKernelCount > 0 || notebookCellListFocused && !notebookCellExecuting && notebookCellType == 'code' && notebookKernelSourceCount > 0"
    intellij:
      action: "RunCellAndInsertBelowAction"
    zed:
      notSupported: true
      notSupportedReason: "Notebook not supported yet see [issue](https://github.com/zed-industries/zed/discussions/25936)"
  - id: "actions.notebook.cell.executeAndSelectBelow"
    name: "Execute and select"
    description: "Execute Cell and Select Below"
    category: "Tools.Jupyter Notebook"
    vscode:
      command: "notebook.cell.executeAndSelectBelow"
      when: "notebookCellListFocused && !interactiveEditorFocused && notebookCellType == 'code' || editorTextFocus && inputFocus && notebookEditorFocused && !interactiveEditorFocused"
    intellij:
      action: "NotebookRunCellAndSelectBelow"
    zed:
      notSupported: true
      notSupportedReason: "Notebook not supported yet see [issue](https://github.com/zed-industries/zed/discussions/25936)"
  - id: "actions.notebook.cell.insertCodeCellAbove"
    name: "Insert above"
    description: "Insert Code Cell Above"
    category: "Tools.Jupyter Notebook"
    vscode:
      command: "notebook.cell.insertCodeCellAbove"
      when: "notebookCellListFocused && !inputFocus"
    intellij:
      action: "NotebookInsertCodeCellAbove"
    zed:
      notSupported: true
      notSupportedReason: "Notebook not supported yet see [issue](https://github.com/zed-industries/zed/discussions/25936)"
  - id: "actions.notebook.cell.insertCodeCellBelow"
    name: "Insert below"
    description: "Insert Code Cell Below"
    category: "Tools.Jupyter Notebook"
    vscode:
      command: "notebook.cell.insertCodeCellBelow"
      when: "notebookCellListFocused && !inputFocus && notebookChatOuterFocusPosition == ''"
    intellij:
      action: "NotebookInsertCodeCellBelow"
    zed:
      notSupported: true
      notSupportedReason: "Notebook not supported yet see [issue](https://github.com/zed-industries/zed/discussions/25936)"
  - id: "actions.notebook.cell.moveDown"
    name: "Move down"
    description: "Move Cell Down"
    category: "Tools.Jupyter Notebook"
    vscode:
      command: "notebook.cell.moveDown"
      when: "notebookEditorFocused && !inputFocus"
    intellij:
      action: "MoveStatementDown"
    zed:
      notSupported: true
      notSupportedReason: "Notebook not supported yet see [issue](https://github.com/zed-industries/zed/discussions/25936)"
  - id: "actions.notebook.cell.moveUp"
    name: "Move up"
    description: "Move Cell Up"
    category: "Tools.Jupyter Notebook"
    vscode:
      command: "notebook.cell.moveUp"
      when: "notebookEditorFocused && !inputFocus"
    intellij:
      action: "MoveStatementUp"
    zed:
      notSupported: true
      notSupportedReason: "Notebook not supported yet see [issue](https://github.com/zed-industries/zed/discussions/25936)"
  - id: "actions.notebook.cell.quitEdit"
    name: "Quit edit"
    description: "Stop Editing Cell"
    category: "Tools.Jupyter Notebook"
    vscode:
      command: "notebook.cell.quitEdit"
      when: "notebookEditorFocused && notebookOutputFocused"
    intellij:
      action: "NotebookExitEditMode"
    zed:
      notSupported: true
      notSupportedReason: "Notebook not supported yet see [issue](https://github.com/zed-industries/zed/discussions/25936)"
  - id: "actions.notebook.focusBottom"
    name: "Focus bottom"
    description: "Focus Bottom"
    category: "Tools.Jupyter Notebook"
    vscode:
      command: "notebook.focusBottom"
      when: "notebookEditorFocused && !inputFocus && notebookChatOuterFocusPosition == ''"
    intellij:
      action: "NotebookSelectLastCell"
    zed:
      notSupported: true
      notSupportedReason: "Notebook not supported yet see [issue](https://github.com/zed-industries/zed/discussions/25936)"
  - id: "actions.notebook.focusTop"
    name: "Focus top"
    description: "Focus Top"
    category: "Tools.Jupyter Notebook"
    vscode:
      command: "notebook.focusTop"
      when: "notebookEditorFocused && !inputFocus && notebookChatOuterFocusPosition == ''"
    intellij:
      action: "NotebookSelectFirstCell"
    zed:
      notSupported: true
      notSupportedReason: "Notebook not supported yet see [issue](https://github.com/zed-industries/zed/discussions/25936)"
