mappings:
  - id: "actions.run.selectionToRepl"
    name: "Evaluate selection"
    description: "Send selection to REPL"
    category: "Debug"
    vscode:
      command: "editor.debug.action.selectionToRepl"
      when: "debuggersAvailable && editorTextFocus && editorHasSelection"
    intellij:
      action: "EvaluateExpression"
    zed:
      action: "debugger::EvaluateSelectedText"
      context: "Workspace"
    helix:
      notSupported: true
