mappings:
  - id: "actions.run.toggleBreakpoint"
    name: "Toggle breakpoint"
    description: "Toggle Breakpoint"
    category: "Debug"
    vscode:
      command: "editor.debug.action.toggleBreakpoint"
      when: "debuggersAvailable && disassemblyViewFocus || debuggersAvailable && editorTextFocus"
    zed:
      action: "editor::ToggleBreakpoint"
      context: "Editor"
    intellij:
      action: "ToggleLineBreakpoint"
    helix:
      command: "dap_toggle_breakpoint"
      mode: "insert"
