mappings:
  - id: "actions.selection.selectAll"
    name: "Select all"
    description: "Select all text in the editor"
    category: "Editor.Selection"
    vscode:
      command: "editor.action.selectAll"
      when: "textInputFocus"
    zed:
      action: "editor::SelectAll"
      context: "Editor"
    intellij:
      action: "SelectAll"
    helix:
      command: "select_all"
      mode: "insert"
  - id: "actions.selection.expand"
    name: "Expand selection"
    description: "Expand selection"
    category: "Editor.Selection"
    vscode:
      command: "editor.action.smartSelect.expand"
      when: "editorTextFocus"
    zed:
      action: "editor::SelectLargerSyntaxNode"
      context: "Editor"
    intellij:
      action: "EditorSelectWord"
    helix:
      command: "expand_selection"
      mode: "insert"
  - id: "actions.selection.shrink"
    name: "Shrink selection"
    description: "Shrink selection"
    category: "Editor.Selection"
    vscode:
      command: "editor.action.smartSelect.shrink"
      when: "editorTextFocus"
    zed:
      action: "editor::SelectSmallerSyntaxNode"
      context: "Editor"
    intellij:
      action: "EditorUnSelectWord"
    helix:
      command: "shrink_selection"
      mode: "insert"
