mappings:
  - id: "actions.view.toggleStatusBar"
    name: "Toggle status bar"
    description: "Toggle Status Bar visibility"
    category: "View Management"
    vscode:
      command: "workbench.action.toggleStatusbarVisibility"
      when: ""
    zed:
      notSupported: true
      notSupportedReason: "Not support, see [Add options to hide title and status bar issue](https://github.com/zed-industries/zed/issues/5120)"
    # intellij need configure in settings
    intellij:
      notSupported: true
    helix:
      notSupported: true
