// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: keymap/v1/editor.proto

package keymapv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EditorType represents the type of editor.
type EditorType int32

const (
	// Unspecified
	EditorType_EDITOR_TYPE_UNSPECIFIED EditorType = 0
	// VSCode series
	// Visual Studio Code
	EditorType_VSCODE EditorType = 1
	// WindSurf
	EditorType_WINDSURF EditorType = 5
	// WindSurf preview
	EditorType_WINDSURF_NEXT EditorType = 6
	// Cursor
	EditorType_CURSOR EditorType = 7
	// Zed
	EditorType_ZED EditorType = 2
	// IntelliJ series
	// IntelliJ IDEA Ultimate
	EditorType_INTELLIJ EditorType = 8
	// IntelliJ IDEA Community
	EditorType_INTELLIJ_COMMUNITY EditorType = 9
	// PyCharm
	EditorType_PYCHARM EditorType = 10
	// WebStorm
	EditorType_WEBSTORM EditorType = 11
	// CLion
	EditorType_CLION EditorType = 12
	// PhpStorm
	EditorType_PHPSTORM EditorType = 13
	// RubyMine
	EditorType_RUBYMINE EditorType = 14
	// GoLand
	EditorType_GOLAND EditorType = 15
	// RustRover
	EditorType_RUSTROVER EditorType = 16
	// Helix
	EditorType_HELIX EditorType = 3
	// Vim
	EditorType_VIM   EditorType = 4
	EditorType_XCODE EditorType = 17
)

// Enum value maps for EditorType.
var (
	EditorType_name = map[int32]string{
		0:  "EDITOR_TYPE_UNSPECIFIED",
		1:  "VSCODE",
		5:  "WINDSURF",
		6:  "WINDSURF_NEXT",
		7:  "CURSOR",
		2:  "ZED",
		8:  "INTELLIJ",
		9:  "INTELLIJ_COMMUNITY",
		10: "PYCHARM",
		11: "WEBSTORM",
		12: "CLION",
		13: "PHPSTORM",
		14: "RUBYMINE",
		15: "GOLAND",
		16: "RUSTROVER",
		3:  "HELIX",
		4:  "VIM",
		17: "XCODE",
	}
	EditorType_value = map[string]int32{
		"EDITOR_TYPE_UNSPECIFIED": 0,
		"VSCODE":                  1,
		"WINDSURF":                5,
		"WINDSURF_NEXT":           6,
		"CURSOR":                  7,
		"ZED":                     2,
		"INTELLIJ":                8,
		"INTELLIJ_COMMUNITY":      9,
		"PYCHARM":                 10,
		"WEBSTORM":                11,
		"CLION":                   12,
		"PHPSTORM":                13,
		"RUBYMINE":                14,
		"GOLAND":                  15,
		"RUSTROVER":               16,
		"HELIX":                   3,
		"VIM":                     4,
		"XCODE":                   17,
	}
)

func (x EditorType) Enum() *EditorType {
	p := new(EditorType)
	*p = x
	return p
}

func (x EditorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EditorType) Descriptor() protoreflect.EnumDescriptor {
	return file_keymap_v1_editor_proto_enumTypes[0].Descriptor()
}

func (EditorType) Type() protoreflect.EnumType {
	return &file_keymap_v1_editor_proto_enumTypes[0]
}

func (x EditorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EditorType.Descriptor instead.
func (EditorType) EnumDescriptor() ([]byte, []int) {
	return file_keymap_v1_editor_proto_rawDescGZIP(), []int{0}
}

var File_keymap_v1_editor_proto protoreflect.FileDescriptor

const file_keymap_v1_editor_proto_rawDesc = "" +
	"\n" +
	"\x16keymap/v1/editor.proto\x12\tkeymap.v1*\x8d\x02\n" +
	"\n" +
	"EditorType\x12\x1b\n" +
	"\x17EDITOR_TYPE_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06VSCODE\x10\x01\x12\f\n" +
	"\bWINDSURF\x10\x05\x12\x11\n" +
	"\rWINDSURF_NEXT\x10\x06\x12\n" +
	"\n" +
	"\x06CURSOR\x10\a\x12\a\n" +
	"\x03ZED\x10\x02\x12\f\n" +
	"\bINTELLIJ\x10\b\x12\x16\n" +
	"\x12INTELLIJ_COMMUNITY\x10\t\x12\v\n" +
	"\aPYCHARM\x10\n" +
	"\x12\f\n" +
	"\bWEBSTORM\x10\v\x12\t\n" +
	"\x05CLION\x10\f\x12\f\n" +
	"\bPHPSTORM\x10\r\x12\f\n" +
	"\bRUBYMINE\x10\x0e\x12\n" +
	"\n" +
	"\x06GOLAND\x10\x0f\x12\r\n" +
	"\tRUSTROVER\x10\x10\x12\t\n" +
	"\x05HELIX\x10\x03\x12\a\n" +
	"\x03VIM\x10\x04\x12\t\n" +
	"\x05XCODE\x10\x11B\x9c\x01\n" +
	"\rcom.keymap.v1B\vEditorProtoP\x01Z9github.com/xinnjie/watchbeats/protogen/keymap/v1;keymapv1\xa2\x02\x03KXX\xaa\x02\tKeymap.V1\xca\x02\tKeymap\\V1\xe2\x02\x15Keymap\\V1\\GPBMetadata\xea\x02\n" +
	"Keymap::V1b\x06proto3"

var (
	file_keymap_v1_editor_proto_rawDescOnce sync.Once
	file_keymap_v1_editor_proto_rawDescData []byte
)

func file_keymap_v1_editor_proto_rawDescGZIP() []byte {
	file_keymap_v1_editor_proto_rawDescOnce.Do(func() {
		file_keymap_v1_editor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_keymap_v1_editor_proto_rawDesc), len(file_keymap_v1_editor_proto_rawDesc)))
	})
	return file_keymap_v1_editor_proto_rawDescData
}

var file_keymap_v1_editor_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_keymap_v1_editor_proto_goTypes = []any{
	(EditorType)(0), // 0: keymap.v1.EditorType
}
var file_keymap_v1_editor_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_keymap_v1_editor_proto_init() }
func file_keymap_v1_editor_proto_init() {
	if File_keymap_v1_editor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_keymap_v1_editor_proto_rawDesc), len(file_keymap_v1_editor_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_keymap_v1_editor_proto_goTypes,
		DependencyIndexes: file_keymap_v1_editor_proto_depIdxs,
		EnumInfos:         file_keymap_v1_editor_proto_enumTypes,
	}.Build()
	File_keymap_v1_editor_proto = out.File
	file_keymap_v1_editor_proto_goTypes = nil
	file_keymap_v1_editor_proto_depIdxs = nil
}
