// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: keymap/v1/editor.proto

package keymapv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EditorType represents the type of editor.
type EditorType int32

const (
	// Unspecified
	EditorType_EDITOR_TYPE_UNSPECIFIED EditorType = 0
	// Visual Studio Code
	EditorType_VSCODE EditorType = 1
	// Zed
	EditorType_ZED EditorType = 2
	// IntelliJ
	EditorType_INTELLIJ EditorType = 3
	// Helix
	EditorType_HELIX EditorType = 4
)

// Enum value maps for EditorType.
var (
	EditorType_name = map[int32]string{
		0: "EDITOR_TYPE_UNSPECIFIED",
		1: "VSCODE",
		2: "ZED",
		3: "INTELLIJ",
		4: "HELIX",
	}
	EditorType_value = map[string]int32{
		"EDITOR_TYPE_UNSPECIFIED": 0,
		"VSCODE":                  1,
		"ZED":                     2,
		"INTELLIJ":                3,
		"HELIX":                   4,
	}
)

func (x EditorType) Enum() *EditorType {
	p := new(EditorType)
	*p = x
	return p
}

func (x EditorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EditorType) Descriptor() protoreflect.EnumDescriptor {
	return file_keymap_v1_editor_proto_enumTypes[0].Descriptor()
}

func (EditorType) Type() protoreflect.EnumType {
	return &file_keymap_v1_editor_proto_enumTypes[0]
}

func (x EditorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EditorType.Descriptor instead.
func (EditorType) EnumDescriptor() ([]byte, []int) {
	return file_keymap_v1_editor_proto_rawDescGZIP(), []int{0}
}

var File_keymap_v1_editor_proto protoreflect.FileDescriptor

const file_keymap_v1_editor_proto_rawDesc = "" +
	"\n" +
	"\x16keymap/v1/editor.proto\x12\tkeymap.v1*W\n" +
	"\n" +
	"EditorType\x12\x1b\n" +
	"\x17EDITOR_TYPE_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06VSCODE\x10\x01\x12\a\n" +
	"\x03ZED\x10\x02\x12\f\n" +
	"\bINTELLIJ\x10\x03\x12\t\n" +
	"\x05HELIX\x10\x04B\x9c\x01\n" +
	"\rcom.keymap.v1B\vEditorProtoP\x01Z9github.com/xinnjie/watchbeats/protogen/keymap/v1;keymapv1\xa2\x02\x03KXX\xaa\x02\tKeymap.V1\xca\x02\tKeymap\\V1\xe2\x02\x15Keymap\\V1\\GPBMetadata\xea\x02\n" +
	"Keymap::V1b\x06proto3"

var (
	file_keymap_v1_editor_proto_rawDescOnce sync.Once
	file_keymap_v1_editor_proto_rawDescData []byte
)

func file_keymap_v1_editor_proto_rawDescGZIP() []byte {
	file_keymap_v1_editor_proto_rawDescOnce.Do(func() {
		file_keymap_v1_editor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_keymap_v1_editor_proto_rawDesc), len(file_keymap_v1_editor_proto_rawDesc)))
	})
	return file_keymap_v1_editor_proto_rawDescData
}

var file_keymap_v1_editor_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_keymap_v1_editor_proto_goTypes = []any{
	(EditorType)(0), // 0: keymap.v1.EditorType
}
var file_keymap_v1_editor_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_keymap_v1_editor_proto_init() }
func file_keymap_v1_editor_proto_init() {
	if File_keymap_v1_editor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_keymap_v1_editor_proto_rawDesc), len(file_keymap_v1_editor_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_keymap_v1_editor_proto_goTypes,
		DependencyIndexes: file_keymap_v1_editor_proto_depIdxs,
		EnumInfos:         file_keymap_v1_editor_proto_enumTypes,
	}.Build()
	File_keymap_v1_editor_proto = out.File
	file_keymap_v1_editor_proto_goTypes = nil
	file_keymap_v1_editor_proto_depIdxs = nil
}
