// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: keymap/v1/platform.proto

package keymapv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Platform represents the platform type.
type Platform int32

const (
	// Unspecified
	Platform_PLATFORM_UNSPECIFIED Platform = 0
	// MacOS
	Platform_MACOS Platform = 1
	// Windows, not support yet
	Platform_WINDOWS Platform = 2
	// Linux, not support yet
	Platform_LINUX Platform = 3
)

// Enum value maps for Platform.
var (
	Platform_name = map[int32]string{
		0: "PLATFORM_UNSPECIFIED",
		1: "MACOS",
		2: "WINDOWS",
		3: "LINUX",
	}
	Platform_value = map[string]int32{
		"PLATFORM_UNSPECIFIED": 0,
		"MACOS":                1,
		"WINDOWS":              2,
		"LINUX":                3,
	}
)

func (x Platform) Enum() *Platform {
	p := new(Platform)
	*p = x
	return p
}

func (x Platform) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Platform) Descriptor() protoreflect.EnumDescriptor {
	return file_keymap_v1_platform_proto_enumTypes[0].Descriptor()
}

func (Platform) Type() protoreflect.EnumType {
	return &file_keymap_v1_platform_proto_enumTypes[0]
}

func (x Platform) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Platform.Descriptor instead.
func (Platform) EnumDescriptor() ([]byte, []int) {
	return file_keymap_v1_platform_proto_rawDescGZIP(), []int{0}
}

var File_keymap_v1_platform_proto protoreflect.FileDescriptor

const file_keymap_v1_platform_proto_rawDesc = "" +
	"\n" +
	"\x18keymap/v1/platform.proto\x12\tkeymap.v1*G\n" +
	"\bPlatform\x12\x18\n" +
	"\x14PLATFORM_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05MACOS\x10\x01\x12\v\n" +
	"\aWINDOWS\x10\x02\x12\t\n" +
	"\x05LINUX\x10\x03B\x9e\x01\n" +
	"\rcom.keymap.v1B\rPlatformProtoP\x01Z9github.com/xinnjie/watchbeats/protogen/keymap/v1;keymapv1\xa2\x02\x03KXX\xaa\x02\tKeymap.V1\xca\x02\tKeymap\\V1\xe2\x02\x15Keymap\\V1\\GPBMetadata\xea\x02\n" +
	"Keymap::V1b\x06proto3"

var (
	file_keymap_v1_platform_proto_rawDescOnce sync.Once
	file_keymap_v1_platform_proto_rawDescData []byte
)

func file_keymap_v1_platform_proto_rawDescGZIP() []byte {
	file_keymap_v1_platform_proto_rawDescOnce.Do(func() {
		file_keymap_v1_platform_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_keymap_v1_platform_proto_rawDesc), len(file_keymap_v1_platform_proto_rawDesc)))
	})
	return file_keymap_v1_platform_proto_rawDescData
}

var file_keymap_v1_platform_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_keymap_v1_platform_proto_goTypes = []any{
	(Platform)(0), // 0: keymap.v1.Platform
}
var file_keymap_v1_platform_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_keymap_v1_platform_proto_init() }
func file_keymap_v1_platform_proto_init() {
	if File_keymap_v1_platform_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_keymap_v1_platform_proto_rawDesc), len(file_keymap_v1_platform_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_keymap_v1_platform_proto_goTypes,
		DependencyIndexes: file_keymap_v1_platform_proto_depIdxs,
		EnumInfos:         file_keymap_v1_platform_proto_enumTypes,
	}.Build()
	File_keymap_v1_platform_proto = out.File
	file_keymap_v1_platform_proto_goTypes = nil
	file_keymap_v1_platform_proto_depIdxs = nil
}
